name: Release

on:
  push:
    branches:
      - master
      - ci-add-pipeline
    paths:
      - 'src/**'
      - '.github/workflows/release.yml'
  pull_request:
    branches:
      - master
      - ci-add-pipeline
    paths:
      - 'src/**'
      - '.github/workflows/release.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      
      - name: Install node_modules
        run: npm install
      
      - name: Build with Electron-Forge
        run: npx electron-forge make --arch "x64" --platform "win32"

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          path: ./out/make/zip/win32/x64/*.zip